# Generated by Django 5.0.1 on 2024-03-01 19:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AcademPy', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('cod_escolar', models.CharField(max_length=10)),
            ],
        ),
        migrations.RenameField(
            model_name='professores',
            old_name='cod_escola',
            new_name='cod_escolar',
        ),
    ]
