# Generated by Django 5.0.1 on 2024-03-04 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AcademPy', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='administrador',
            name='cod_academ',
        ),
        migrations.RemoveField(
            model_name='professor',
            name='cod_academ',
        ),
    ]
