# Generated by Django 5.0.2 on 2024-03-20 03:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AcademPy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professor',
            name='especializacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AcademPy.disciplina'),
        ),
    ]
