# Generated by Django 5.0.1 on 2024-03-18 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AcademPy', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='turma',
            name='qtd_aulas',
        ),
    ]
