# Generated by Django 5.0.1 on 2024-03-01 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AcademPy', '0002_administrador_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='administrador',
            old_name='cod_escolar',
            new_name='cod_academ',
        ),
        migrations.RenameField(
            model_name='professores',
            old_name='cod_escolar',
            new_name='cod_academ',
        ),
    ]
