# Generated by Django 5.0.1 on 2024-03-08 19:32

import AcademPy.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AcademPy', '0002_remove_administrador_cod_academ_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='turma',
            options={'ordering': ['nome']},
        ),
        migrations.CreateModel(
            name='Aula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.IntegerField(choices=[(1, 'Domingo'), (2, 'Segunda'), (3, 'Terça'), (4, 'Quarta'), (5, 'Quinta'), (6, 'Sexta'), (7, 'Sábado')])),
                ('horario', models.IntegerField()),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AcademPy.disciplina')),
                ('professor', models.ForeignKey(on_delete=AcademPy.models.Professor, to='AcademPy.professor')),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AcademPy.turma')),
            ],
        ),
    ]
