# Generated by Django 5.0.1 on 2024-03-13 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AcademPy', '0003_alter_turma_options_aula'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='disciplina',
            options={'ordering': ['nome']},
        ),
    ]
