# Generated by Django 5.0.1 on 2024-03-01 20:40

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AcademPy', '0003_rename_cod_escolar_administrador_cod_academ_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Professores',
            new_name='Professor',
        ),
    ]
