# Generated by Django 5.0.2 on 2024-03-20 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AcademPy', '0004_alter_professor_especializacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professor',
            name='especializacao',
            field=models.CharField(max_length=100),
        ),
    ]
