# Generated by Django 5.0.1 on 2024-03-14 17:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AcademPy', '0004_alter_disciplina_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cronograma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_criacao', models.DateTimeField(auto_now_add=True)),
                ('qtd_aulas', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='turma',
            name='qtd_aulas',
            field=models.IntegerField(default=6),
        ),
        migrations.AlterField(
            model_name='aula',
            name='dia_semana',
            field=models.IntegerField(choices=[(1, 'Domingo'), (2, 'Segunda-Feira'), (3, 'Terça-Feira'), (4, 'Quarta-Feira'), (5, 'Quinta-Feira'), (6, 'Sexta-Feira'), (7, 'Sábado')]),
        ),
        migrations.AlterField(
            model_name='aula',
            name='professor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AcademPy.professor'),
        ),
    ]
