# Generated by Django 5.0.2 on 2024-03-20 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AcademPy', '0005_alter_professor_especializacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aula',
            name='dia_semana',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='aula',
            name='turma',
            field=models.IntegerField(),
        ),
    ]
